import reportRepo from '../repositories/report.repo.js';
import contributionRepo from '../repositories/contribution.repo.js';
import memberRepo from '../repositories/member.repo.js';
import customerRepo from '../repositories/customer.repo.js';
import accountRepo from '../repositories/account.repo.js';
import projectRepo from '../repositories/project.repo.js';
import expenseRepo from '../repositories/expense.repo.js';
import employeeRepo from '../repositories/employee.repo.js';
import statementRepo from '../repositories/statement.repo.js';
import transactionRepo from '../repositories/transaction.repo.js';
import settingsRepo from '../repositories/settings.repo.js';
import exportJobRepo from '../repositories/exportJob.repo.js';
import auditService from './audit.service.js';
import ApiError from '../utils/ApiError.js';
import {
  generateReportPdf,
  generateIncomeStatementPdf,
  generateMemberStatementPdf,
  generateCustomerStatementPdf,
  generateAccountStatementPdf,
  generateAccountBalancesPdf,
  generateCashFlowPdf,
  generateContributionReportPdf,
} from '../helpers/pdf.js';
import { generateExcel } from '../helpers/excel.js';
import dayjs from 'dayjs';

const EXPORT_MAX_ROWS = 2000;

const REPORT_DEFINITIONS = {
  incomeStatement: {
    title: 'Income Statement',
    columns: [
      { header: 'Metric', key: 'label' },
      { header: 'Amount', key: 'value' },
    ],
    build: (data) => [
      { label: 'Total Income', value: data.total_income },
      { label: 'Total Expenses', value: data.total_expense },
      { label: 'Net Profit / (Loss)', value: data.net_profit },
    ],
  },
  monthlyRevenue: {
    title: 'Monthly Revenue & Expenses',
    columns: [
      { header: 'Month', key: 'month' },
      { header: 'Income', key: 'income' },
      { header: 'Expenses', key: 'expense' },
      { header: 'Net', key: 'net' },
    ],
    build: (rows) => rows,
  },
  cashFlow: {
    title: 'Cash Flow',
    columns: [
      { header: 'Month', key: 'month' },
      { header: 'Inflow', key: 'inflow' },
      { header: 'Outflow', key: 'outflow' },
      { header: 'Net', key: 'net' },
    ],
    build: (rows) => rows,
  },
  cashFlowDetails: {
    title: 'Cash Flow Transactions',
    columns: [
      { header: 'Description', key: 'description', width: 40 },
      { header: 'Date', key: 'date', width: 14 },
      { header: 'Time', key: 'time', width: 10 },
      { header: 'Inflow (in)', key: 'inflow', width: 14 },
      { header: 'Outflow (out)', key: 'outflow', width: 14 },
      { header: 'Net', key: 'net', width: 14 },
      { header: 'Balance', key: 'balance', width: 14 },
    ],
    build: (rows) => rows,
  },
  rentalRevenue: {
    title: 'Rental Revenue',
    columns: [
      { header: 'Total Rental Income', key: 'total' },
      { header: 'Billings Count', key: 'billings' },
    ],
    build: (data) => [
      { total: data.total, billings: data.billings },
    ],
  },
  outstandingCustomers: {
    title: 'Outstanding Customer Balances',
    columns: [
      { header: 'Customer', key: 'customer_name' },
      { header: 'Company', key: 'company_name' },
      { header: 'Phone', key: 'phone' },
      { header: 'Outstanding', key: 'outstanding' },
      { header: 'Open Invoices', key: 'open_invoices' },
    ],
    build: (rows) => rows,
  },
  customerPaymentStatus: {
    title: 'Customer Payment Status',
    columns: [
      { header: 'Customer', key: 'customer_name' },
      { header: 'Code', key: 'customer_code' },
      { header: 'Status', key: 'payment_status' },
      { header: 'Invoiced', key: 'total_invoiced' },
      { header: 'Paid', key: 'total_paid' },
      { header: 'Outstanding', key: 'outstanding' },
      { header: 'Last payment', key: 'last_payment_at' },
      { header: 'Open Invoices', key: 'open_invoices' },
    ],
    build: (rows) => rows,
  },
  expenseByCategory: {
    title: 'Expenses by Category',
    columns: [
      { header: 'Category', key: 'category_name' },
      { header: 'Total', key: 'total' },
      { header: 'Count', key: 'count' },
    ],
    build: (rows) => rows,
  },
  contributionReport: {
    title: 'Member Contributions',
    columns: [
      { header: 'Month / Year', key: 'period' },
      { header: 'Generated By', key: 'generated_by' },
      { header: 'Dues', key: 'total_dues' },
      { header: 'Expected', key: 'expected' },
      { header: 'Collected', key: 'collected' },
      { header: 'Pending', key: 'pending' },
      { header: 'Partial', key: 'partial' },
      { header: 'Paid', key: 'paid' },
    ],
    build: (data) => [
      {
        period: `${data.month}/${data.year}`,
        generated_by: data.generated_by,
        total_dues: data.total_dues,
        expected: data.expected,
        collected: data.collected,
        pending: data.pending,
        partial: data.partial,
        paid: data.paid,
      },
    ],
  },
  projectReport: {
    title: 'Projects by Status',
    columns: [
      { header: 'Status', key: 'status' },
      { header: 'Count', key: 'count' },
      { header: 'Value', key: 'value' },
    ],
    build: (rows) => rows,
  },
  memberStatement: {
    title: 'Member Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit', key: 'due' },
      { header: 'Credit', key: 'paid' },
      { header: 'Loan', key: 'loan' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
  customerStatement: {
    title: 'Customer Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit', key: 'debit' },
      { header: 'Credit', key: 'credit' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
  projectStatement: {
    title: 'Project Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit', key: 'debit' },
      { header: 'Credit', key: 'credit' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
  expenseStatement: {
    title: 'Expense Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Name', key: 'name' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit', key: 'debit' },
      { header: 'Credit', key: 'credit' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
  salaryStatement: {
    title: 'Salary Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit', key: 'debit' },
      { header: 'Credit', key: 'credit' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
  employeeList: {
    title: 'Employees',
    columns: [
      { header: 'Code', key: 'employee_code' },
      { header: 'Name', key: 'full_name' },
      { header: 'Phone', key: 'phone' },
      { header: 'Gender', key: 'gender' },
      { header: 'Job title', key: 'job_title' },
      { header: 'Department', key: 'department' },
      { header: 'Branch', key: 'branch' },
      { header: 'Shift', key: 'shift' },
      { header: 'Hire date', key: 'hire_date' },
      { header: 'Basic salary', key: 'basic_salary' },
      { header: 'Status', key: 'status' },
    ],
    build: (data) => data.rows ?? [],
  },
  employeeReport: {
    title: 'Employee Report',
    columns: [
      { header: 'Field', key: 'label' },
      { header: 'Value', key: 'value' },
    ],
    build: (data) => data.rows ?? [],
  },
  accountBalances: {
    title: 'Account Balances',
    columns: [
      { header: 'Institution', key: 'institution' },
      { header: 'Account #', key: 'number' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => [
      ...(data.accounts ?? []).map((a) => ({
        institution: `${a.institution}${a.is_default ? ' (Default)' : ''}`,
        number: a.number,
        balance: Number(a.balance ?? 0),
      })),
      { institution: 'TOTAL', number: '', balance: Number(data.total ?? 0) },
    ],
  },
  accountStatement: {
    title: 'Account Statement',
    columns: [
      { header: 'Date', key: 'date' },
      { header: 'Time', key: 'time' },
      { header: 'Type', key: 'type' },
      { header: 'Reference', key: 'reference' },
      { header: 'Debit (in)', key: 'debit' },
      { header: 'Credit (out)', key: 'credit' },
      { header: 'Loan', key: 'loan' },
      { header: 'Balance', key: 'balance' },
    ],
    build: (data) => data.rows ?? [],
  },
};

export const reportService = {
  async incomeStatement(fromDate, toDate) {
    return reportRepo.incomeStatement(null, { fromDate, toDate });
  },

  async monthlyRevenue(months) {
    return reportRepo.monthlySummary(null, months);
  },

  async cashFlow(fromDate, toDate) {
    return reportRepo.cashFlow(null, fromDate, toDate);
  },

  async cashFlowDetails(fromDate, toDate) {
    const rows = await transactionRepo.list(null, {
      fromDate,
      toDate,
      offset: 0,
      perPage: EXPORT_MAX_ROWS,
      order: 'transaction_id ASC',
    });
    let balance = 0;
    let totalInflow = 0;
    let totalOutflow = 0;
    const detailRows = rows.map((row) => {
      const income = Number(row.income ?? 0);
      const expense = Number(row.expense ?? 0);
      const net = Math.round((income - expense) * 100) / 100;
      balance = Math.round((balance + net) * 100) / 100;
      totalInflow += income;
      totalOutflow += expense;
      return {
        description: row.description || `${row.reference_type ?? 'Transaction'} #${row.reference_id ?? ''}`,
        date: dayjs(row.transaction_date).format('DD MMM YYYY'),
        time: dayjs(row.created_at ?? row.transaction_date).format('HH:mm'),
        inflow: income > 0 ? income : '',
        outflow: expense > 0 ? expense : '',
        net,
        balance,
      };
    });
    const netTotal = Math.round((totalInflow - totalOutflow) * 100) / 100;
    detailRows.push({
      description: 'Total',
      date: '',
      time: '',
      inflow: Math.round(totalInflow * 100) / 100,
      outflow: Math.round(totalOutflow * 100) / 100,
      net: netTotal,
      balance,
    });
    return detailRows;
  },

  async rentalRevenue(fromDate, toDate) {
    return reportRepo.rentalRevenue(null, fromDate, toDate);
  },

  async outstandingCustomers() {
    return reportRepo.outstandingCustomers(null);
  },

  async customerPaymentStatus() {
    const rows = await reportRepo.customerPaymentStatus(null);
    return rows.map((row) => {
      const outstanding = Number(row.outstanding ?? 0);
      const totalInvoiced = Number(row.total_invoiced ?? 0);
      const totalPaid = Number(row.total_paid ?? 0);
      let payment_status = 'Clear';
      if (outstanding > 0) {
        payment_status = totalPaid > 0 ? 'Partial' : 'Unpaid';
      } else if (totalInvoiced > 0) {
        payment_status = 'Paid';
      }
      return { ...row, payment_status };
    });
  },

  async expenseByCategory(fromDate, toDate) {
    return reportRepo.expenseByCategory(null, fromDate, toDate);
  },

  async contributionReport(batchId) {
    const data = await reportRepo.contributionReport(null, batchId);
    if (!data) throw ApiError.notFound('Due batch not found');
    const dues = await contributionRepo.listDues(null, {
      batchId,
      status: '',
      memberId: '',
      offset: 0,
      perPage: EXPORT_MAX_ROWS,
      order: 'member_name ASC',
    });
    return { summary: data, dues };
  },

  async projectReport() {
    return reportRepo.projectReport(null);
  },

  async memberStatement(memberId, fromDate, toDate) {
    const member = await memberRepo.findMemberById(null, memberId);
    if (!member) throw ApiError.notFound('Member not found');

    const [rows, outstanding, creditBalance] = await Promise.all([
      statementRepo.member(null, memberId, fromDate, toDate),
      contributionRepo.memberOutstanding(null, memberId),
      contributionRepo.getMemberCreditBalance(null, memberId),
    ]);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      member: {
        member_id: member.member_id,
        member_name: member.member_name,
        position: member.position,
        email: member.email,
        phone: member.phone,
        joined_date: member.joined_date,
        loan_balance: creditBalance,
        credit_balance: creditBalance,
      },
      totals: {
        charged: fnTotals.debit,
        loans: fnTotals.loan,
        paid: fnTotals.credit,
        outstanding,
        loan_balance: creditBalance,
        closing_balance: fnTotals.closing_balance,
        credit_balance: creditBalance,
      },
      rows,
    };
  },

  async customerStatement(customerId, fromDate, toDate) {
    const customer = await customerRepo.findById(null, customerId);
    if (!customer) throw ApiError.notFound('Customer not found');

    const rows = await statementRepo.customer(null, customerId, fromDate, toDate);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      customer: {
        customer_id: customer.customer_id,
        customer_name: customer.customer_name,
        customer_code: customer.customer_code,
        company_name: customer.company_name,
        phone: customer.phone,
        email: customer.email,
      },
      totals: {
        invoiced: fnTotals.debit,
        paid: fnTotals.credit,
        outstanding: fnTotals.closing_balance,
        closing_balance: fnTotals.closing_balance,
      },
      rows,
    };
  },

  async projectStatement(projectId, fromDate, toDate) {
    const project = await projectRepo.findById(null, projectId);
    if (!project) throw ApiError.notFound('Project not found');

    const rows = await statementRepo.project(null, projectId, fromDate, toDate);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      project: {
        project_id: project.project_id,
        project_name: project.project_name,
        project_code: project.project_code,
        status: project.status,
      },
      totals: {
        invoiced: fnTotals.debit,
        paid: fnTotals.credit,
        outstanding: fnTotals.closing_balance,
        closing_balance: fnTotals.closing_balance,
      },
      rows,
    };
  },

  async expenseStatement(expenseId, fromDate, toDate) {
    const id = Number(expenseId) || 0;
    const expense = id
      ? await expenseRepo.findCategoryById(null, id)
      : { expense_id: 0, expense_name: 'All expenses', expense_code: 'ALL' };
    if (!expense) throw ApiError.notFound('Expense category not found');

    const rows = await statementRepo.expense(null, id, fromDate, toDate);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      expense: {
        expense_id: expense.expense_id,
        expense_name: expense.expense_name,
        expense_code: expense.expense_code,
      },
      totals: {
        charged: fnTotals.debit,
        paid: fnTotals.credit,
        outstanding: fnTotals.closing_balance,
        closing_balance: fnTotals.closing_balance,
      },
      rows,
    };
  },

  async salaryStatement(employeeId, fromDate, toDate) {
    const employee = await employeeRepo.findById(null, employeeId);
    if (!employee) throw ApiError.notFound('Employee not found');

    const rows = await statementRepo.salary(null, employeeId, fromDate, toDate);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      employee: {
        employee_id: employee.employee_id,
        employee_code: employee.employee_code,
        full_name: employee.full_name,
        phone: employee.phone,
        job_title: employee.job_title,
      },
      totals: {
        charged: fnTotals.debit,
        paid: fnTotals.credit,
        outstanding: fnTotals.closing_balance,
        closing_balance: fnTotals.closing_balance,
      },
      rows,
    };
  },

  async employeeList(fromDate, toDate) {
    const rows = await employeeRepo.list(null, {
      offset: 0,
      perPage: 500,
      order: 'first_name ASC, last_name ASC',
    });
    const from = fromDate ? String(fromDate).slice(0, 10) : '';
    const to = toDate ? String(toDate).slice(0, 10) : '';
    const filtered = rows.filter((e) => {
      const hire = e.hire_date instanceof Date
        ? `${e.hire_date.getFullYear()}-${String(e.hire_date.getMonth() + 1).padStart(2, '0')}-${String(e.hire_date.getDate()).padStart(2, '0')}`
        : String(e.hire_date ?? '').slice(0, 10);
      if (from && hire < from) return false;
      if (to && hire > to) return false;
      return true;
    });
    return {
      rows: filtered.map((e) => ({
        employee_code: e.employee_code,
        full_name: e.full_name,
        phone: e.phone || '—',
        gender: e.gender || '—',
        job_title: e.job_title || '—',
        department: e.department || '—',
        branch: e.branch || '—',
        shift: e.shift || '—',
        hire_date: String(e.hire_date ?? '').slice(0, 10) || '—',
        basic_salary: Number(e.basic_salary ?? 0).toFixed(2),
        status: e.status,
      })),
    };
  },

  async employeeReport(employeeId) {
    const employee = await employeeRepo.findById(null, employeeId);
    if (!employee) throw ApiError.notFound('Employee not found');
    const hire = employee.hire_date instanceof Date ? employee.hire_date : employee.hire_date ? new Date(employee.hire_date) : null;
    const hireDate =
      hire && !Number.isNaN(hire.getTime())
        ? `${hire.getFullYear()}-${String(hire.getMonth() + 1).padStart(2, '0')}-${String(hire.getDate()).padStart(2, '0')}`
        : '—';
    return {
      employee,
      rows: [
        { label: 'Code', value: employee.employee_code },
        { label: 'Name', value: employee.full_name },
        { label: 'Phone', value: employee.phone || '—' },
        { label: 'Email', value: employee.email || '—' },
        { label: 'Gender', value: employee.gender || '—' },
        { label: 'Job title', value: employee.job_title || '—' },
        { label: 'Department', value: employee.department || '—' },
        { label: 'Branch', value: employee.branch || '—' },
        { label: 'Shift', value: employee.shift || '—' },
        { label: 'Hire date', value: hireDate },
        { label: 'Basic salary', value: Number(employee.basic_salary ?? 0).toFixed(2) },
        { label: 'Status', value: employee.status },
        { label: 'Address', value: employee.address || '—' },
        { label: 'Notes', value: employee.notes || '—' },
      ],
    };
  },

  async accountBalances() {
    const accounts = await accountRepo.list(null);
    const total = accounts.reduce((sum, a) => sum + Number(a.balance ?? 0), 0);
    return { accounts, total };
  },

  async accountStatement(accId, fromDate, toDate) {
    const account = await accountRepo.findById(null, accId);
    if (!account) throw ApiError.notFound('Account not found');

    const rows = await statementRepo.account(null, accId, fromDate, toDate);
    const fnTotals = statementRepo.totalsFromRows(rows);

    return {
      account,
      totals: {
        debits: fnTotals.debit,
        credits: fnTotals.credit,
        loans: fnTotals.loan,
        balance: Number(account.balance ?? 0),
        closing_balance: fnTotals.closing_balance,
      },
      rows,
    };
  },

  /**
   * Generate a PDF or Excel export for a report kind.
   * Returns { filename, filePath }.
   */
  async export(kind, { fromDate, toDate, months, batchId, memberId, customerId, accId, projectId, expenseId, employeeId }, format, userId, ip) {
    const def = REPORT_DEFINITIONS[kind];
    if (!def) throw ApiError.badRequest(`Unknown report kind '${kind}'`);
    if (!['pdf', 'xlsx'].includes(format)) throw ApiError.badRequest('Format must be pdf or xlsx');

    let data;
    switch (kind) {
      case 'incomeStatement':
        data = await this.incomeStatement(fromDate, toDate);
        break;
      case 'monthlyRevenue':
        data = await this.monthlyRevenue(months || 12);
        break;
      case 'cashFlow':
        data = await this.cashFlowDetails(fromDate, toDate);
        break;
      case 'rentalRevenue':
        data = await this.rentalRevenue(fromDate, toDate);
        break;
      case 'outstandingCustomers':
        data = await this.outstandingCustomers();
        break;
      case 'customerPaymentStatus':
        data = await this.customerPaymentStatus();
        break;
      case 'expenseByCategory':
        data = await this.expenseByCategory(fromDate, toDate);
        break;
      case 'contributionReport': {
        let id = batchId;
        if (!id) {
          const batches = await contributionRepo.listBatches(null, {
            offset: 0,
            perPage: 1,
            order: 'batch_id DESC',
          });
          id = batches[0]?.batch_id;
        }
        if (!id) throw ApiError.badRequest('No contribution batch available to export');
        data = await this.contributionReport(id);
        break;
      }
      case 'projectReport':
        data = await this.projectReport();
        break;
      case 'memberStatement': {
        if (!memberId) throw ApiError.badRequest('member_id is required');
        data = await this.memberStatement(memberId, fromDate, toDate);
        break;
      }
      case 'customerStatement': {
        if (!customerId) throw ApiError.badRequest('customer_id is required');
        data = await this.customerStatement(customerId, fromDate, toDate);
        break;
      }
      case 'accountBalances':
        data = await this.accountBalances();
        break;
      case 'accountStatement': {
        if (!accId) throw ApiError.badRequest('acc_id is required');
        data = await this.accountStatement(accId, fromDate, toDate);
        break;
      }
      case 'projectStatement': {
        if (!projectId) throw ApiError.badRequest('project_id is required');
        data = await this.projectStatement(projectId, fromDate, toDate);
        break;
      }
      case 'expenseStatement': {
        data = await this.expenseStatement(expenseId || 0, fromDate, toDate);
        break;
      }
      case 'salaryStatement': {
        if (!employeeId) throw ApiError.badRequest('employee_id is required');
        data = await this.salaryStatement(employeeId, fromDate, toDate);
        break;
      }
      case 'employeeList':
        data = await this.employeeList(fromDate, toDate);
        break;
      case 'employeeReport': {
        if (!employeeId) throw ApiError.badRequest('employee_id is required');
        data = await this.employeeReport(employeeId);
        break;
      }
      default:
        throw ApiError.badRequest('Unknown report kind');
    }

    const exportData =
      kind === 'contributionReport' && format === 'xlsx' ? data?.summary ?? data : data;
    const rows = def.build(exportData ?? {});
    const exportDef =
      kind === 'cashFlow' ? REPORT_DEFINITIONS.cashFlowDetails : def;
    const subtitle = `Generated ${dayjs().format('DD MMM YYYY HH:mm')}${
      fromDate ? ` · From ${fromDate}` : ''
    }${toDate ? ` · To ${toDate}` : ''}`;
    const settings = await settingsRepo.get(null);

    let result;
    if (format === 'pdf') {
      if (kind === 'incomeStatement') {
        result = await generateIncomeStatementPdf({
          data,
          fromDate,
          toDate,
          settings,
        });
      } else if (kind === 'memberStatement') {
        result = await generateMemberStatementPdf({
          statement: data,
          fromDate,
          toDate,
          settings,
        });
      } else if (kind === 'customerStatement') {
        result = await generateCustomerStatementPdf({
          statement: data,
          fromDate,
          toDate,
          settings,
        });
      } else if (kind === 'accountStatement') {
        result = await generateAccountStatementPdf({
          statement: data,
          fromDate,
          toDate,
          settings,
        });
      } else if (kind === 'accountBalances') {
        result = await generateAccountBalancesPdf({
          data,
          settings,
        });
      } else if (kind === 'cashFlow') {
        result = await generateCashFlowPdf({
          rows: data,
          fromDate,
          toDate,
          settings,
        });
      } else if (kind === 'contributionReport') {
        result = await generateContributionReportPdf({
          report: data,
          settings,
        });
      } else {
        result = await generateReportPdf({
          title: def.title,
          subtitle,
          columns: def.columns,
          rows,
          settings,
        });
      }
    } else {
      const excelRows =
        kind === 'memberStatement'
          ? rows.map((row) => ({
              date: row.date,
              time: row.time,
              type: row.type,
              reference: row.reference,
              due: row.due > 0 ? row.due : '',
              paid: row.paid > 0 ? row.paid : '',
              loan: row.loan > 0 ? row.loan : '',
              balance: row.balance,
            }))
          : kind === 'customerStatement' || kind === 'projectStatement' || kind === 'expenseStatement' || kind === 'salaryStatement'
            ? rows.map((row) => ({
                date: row.date,
                time: row.time,
                type: row.type,
                name: row.name,
                reference: row.reference,
                debit: row.debit > 0 ? row.debit : '',
                credit: row.credit > 0 ? row.credit : '',
                balance: row.balance,
              }))
            : kind === 'accountStatement'
              ? rows.map((row) => ({
                  date: row.date,
                  time: row.time,
                  type: row.type,
                  reference: row.reference,
                  debit: row.debit > 0 ? row.debit : '',
                  credit: row.credit > 0 ? row.credit : '',
                  loan: row.loan > 0 ? row.loan : '',
                  balance: row.balance,
                }))
              : kind === 'cashFlow'
                ? rows.map((row) => ({
                    description: row.description,
                    date: row.date,
                    time: row.time,
                    inflow: row.inflow !== '' && row.inflow != null ? row.inflow : '',
                    outflow: row.outflow !== '' && row.outflow != null ? row.outflow : '',
                    net: row.net,
                    balance: row.balance,
                  }))
                : rows;
      result = await generateExcel({
        title: exportDef.title,
        subtitle,
        columns: exportDef.columns,
        rows: excelRows,
      });
    }

    await auditService.log({ module: 'Report', action: 'EXPORT', userId, ip });
    return result;
  },

  async enqueueExport(kind, params, format, userId, ip) {
    const jobId = await exportJobRepo.create(null, {
      kind,
      format,
      params,
      created_by: userId,
    });
    setImmediate(() => {
      this.processExportJob(jobId, userId, ip).catch(async (err) => {
        await exportJobRepo.markFailed(null, jobId, err?.message || 'Export failed');
      });
    });
    return { jobId, status: 'pending' };
  },

  async processExportJob(jobId, userId, ip) {
    const job = await exportJobRepo.findById(null, jobId);
    if (!job || job.status === 'completed') return null;
    await exportJobRepo.markProcessing(null, jobId);
    const params = typeof job.params === 'string' ? JSON.parse(job.params) : job.params ?? {};
    const result = await this.export(job.kind, params, job.format, userId, ip);
    await exportJobRepo.markCompleted(null, jobId, result.filePath);
    return result;
  },

  async getExportJob(jobId, userId) {
    const job = await exportJobRepo.findById(null, jobId);
    if (!job) throw ApiError.notFound('Export job not found');
    if (job.created_by && job.created_by !== userId) {
      throw ApiError.forbidden('You do not have access to this export job');
    }
    return job;
  },
};

export default reportService;
