import reportRepo from '../repositories/report.repo.js';
import contributionRepo from '../repositories/contribution.repo.js';
import settingsRepo from '../repositories/settings.repo.js';
import auditService from './audit.service.js';
import ApiError from '../utils/ApiError.js';
import { generateReportPdf } from '../helpers/pdf.js';
import { generateExcel } from '../helpers/excel.js';
import dayjs from 'dayjs';

const REPORT_DEFINITIONS = {
  incomeStatement: {
    title: 'Income Statement',
    columns: [
      { header: 'Metric', key: 'label' },
      { header: 'Amount', key: 'value' },
    ],
    build: (data) => [
      { label: 'Total Income', value: data.total_income },
      { label: 'Total Expenses', value: data.total_expense },
      { label: 'Net Profit / (Loss)', value: data.net_profit },
    ],
  },
  monthlyRevenue: {
    title: 'Monthly Revenue & Expenses',
    columns: [
      { header: 'Month', key: 'month' },
      { header: 'Income', key: 'income' },
      { header: 'Expenses', key: 'expense' },
      { header: 'Net', key: 'net' },
    ],
    build: (rows) => rows,
  },
  cashFlow: {
    title: 'Cash Flow',
    columns: [
      { header: 'Month', key: 'month' },
      { header: 'Inflow', key: 'inflow' },
      { header: 'Outflow', key: 'outflow' },
    ],
    build: (rows) => rows,
  },
  rentalRevenue: {
    title: 'Rental Revenue',
    columns: [
      { header: 'Total Rental Income', key: 'total' },
      { header: 'Billings Count', key: 'billings' },
    ],
    build: (data) => [
      { total: data.total, billings: data.billings },
    ],
  },
  outstandingCustomers: {
    title: 'Outstanding Customer Balances',
    columns: [
      { header: 'Customer', key: 'customer_name' },
      { header: 'Company', key: 'company_name' },
      { header: 'Phone', key: 'phone' },
      { header: 'Outstanding', key: 'outstanding' },
      { header: 'Open Invoices', key: 'open_invoices' },
    ],
    build: (rows) => rows,
  },
  expenseByCategory: {
    title: 'Expenses by Category',
    columns: [
      { header: 'Category', key: 'category_name' },
      { header: 'Total', key: 'total' },
      { header: 'Count', key: 'count' },
    ],
    build: (rows) => rows,
  },
  contributionReport: {
    title: 'Member Contributions',
    columns: [
      { header: 'Month / Year', key: 'period' },
      { header: 'Generated By', key: 'generated_by' },
      { header: 'Dues', key: 'total_dues' },
      { header: 'Expected', key: 'expected' },
      { header: 'Collected', key: 'collected' },
      { header: 'Pending', key: 'pending' },
      { header: 'Partial', key: 'partial' },
      { header: 'Paid', key: 'paid' },
    ],
    build: (data) => [
      {
        period: `${data.month}/${data.year}`,
        generated_by: data.generated_by,
        total_dues: data.total_dues,
        expected: data.expected,
        collected: data.collected,
        pending: data.pending,
        partial: data.partial,
        paid: data.paid,
      },
    ],
  },
  projectReport: {
    title: 'Projects by Status',
    columns: [
      { header: 'Status', key: 'status' },
      { header: 'Count', key: 'count' },
      { header: 'Value', key: 'value' },
    ],
    build: (rows) => rows,
  },
};

export const reportService = {
  async incomeStatement(fromDate, toDate) {
    return reportRepo.incomeStatement(null, { fromDate, toDate });
  },

  async monthlyRevenue(months) {
    return reportRepo.monthlySummary(null, months);
  },

  async cashFlow(fromDate, toDate) {
    return reportRepo.cashFlow(null, fromDate, toDate);
  },

  async rentalRevenue(fromDate, toDate) {
    return reportRepo.rentalRevenue(null, fromDate, toDate);
  },

  async outstandingCustomers() {
    return reportRepo.outstandingCustomers(null);
  },

  async expenseByCategory(fromDate, toDate) {
    return reportRepo.expenseByCategory(null, fromDate, toDate);
  },

  async contributionReport(batchId) {
    const data = await reportRepo.contributionReport(null, batchId);
    if (!data) throw ApiError.notFound('Due batch not found');
    const dues = await contributionRepo.listDues(null, {
      batchId,
      status: '',
      memberId: '',
      offset: 0,
      perPage: 10000,
      order: 'member_name ASC',
    });
    return { summary: data, dues };
  },

  async projectReport() {
    return reportRepo.projectReport(null);
  },

  /**
   * Generate a PDF or Excel export for a report kind.
   * Returns { filename, filePath }.
   */
  async export(kind, { fromDate, toDate, months, batchId }, format, userId, ip) {
    const def = REPORT_DEFINITIONS[kind];
    if (!def) throw ApiError.badRequest(`Unknown report kind '${kind}'`);
    if (!['pdf', 'xlsx'].includes(format)) throw ApiError.badRequest('Format must be pdf or xlsx');

    let data;
    switch (kind) {
      case 'incomeStatement':
        data = await this.incomeStatement(fromDate, toDate);
        break;
      case 'monthlyRevenue':
        data = await this.monthlyRevenue(months || 12);
        break;
      case 'cashFlow':
        data = await this.cashFlow(fromDate, toDate);
        break;
      case 'rentalRevenue':
        data = await this.rentalRevenue(fromDate, toDate);
        break;
      case 'outstandingCustomers':
        data = await this.outstandingCustomers();
        break;
      case 'expenseByCategory':
        data = await this.expenseByCategory(fromDate, toDate);
        break;
      case 'contributionReport': {
        let id = batchId;
        if (!id) {
          const batches = await contributionRepo.listBatches(null, {
            offset: 0,
            perPage: 1,
            order: 'batch_id DESC',
          });
          id = batches[0]?.batch_id;
        }
        if (!id) throw ApiError.badRequest('No contribution batch available to export');
        data = (await this.contributionReport(id)).summary;
        break;
      }
      case 'projectReport':
        data = await this.projectReport();
        break;
      default:
        throw ApiError.badRequest('Unknown report kind');
    }

    const rows = def.build(data ?? {});
    const subtitle = `Generated ${dayjs().format('DD MMM YYYY HH:mm')}${
      fromDate ? ` · From ${fromDate}` : ''
    }${toDate ? ` · To ${toDate}` : ''}`;
    const settings = await settingsRepo.get(null);

    let result;
    if (format === 'pdf') {
      result = await generateReportPdf({
        title: def.title,
        subtitle,
        columns: def.columns,
        rows,
        settings,
      });
    } else {
      result = await generateExcel({
        title: def.title,
        subtitle,
        columns: def.columns,
        rows,
      });
    }

    await auditService.log({ module: 'Report', action: 'EXPORT', userId, ip });
    return result;
  },
};

export default reportService;
